/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AppUser {
  all_plants: Generated<boolean>;
  created_at: Generated<Date>;
  display_name: string | null;
  email: string | null;
  is_active: Generated<boolean>;
  password_hash: string | null;
  token_version: Generated<number>;
  updated_at: Generated<Date>;
  user_id: Generated<number>;
  username: string;
}

export interface Asset {
  acquisition_date: Date | null;
  asset_category: Generated<string>;
  asset_id: Generated<number>;
  brand: string | null;
  code: string;
  created_at: Generated<Date>;
  criticality: Generated<string>;
  is_active: Generated<boolean>;
  location: string | null;
  model: string | null;
  name: string;
  notes: string | null;
  parent_asset_id: number | null;
  plant_id: number;
  serial_number: string | null;
  status: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AssetCellAssignment {
  asset_id: number;
  assignment_id: Generated<number>;
  cell_id: number;
  created_at: Generated<Date>;
  created_by: number;
  note: string | null;
  role_label: string | null;
  valid_from: Generated<Date>;
  valid_to: Date | null;
}

export interface AssetDocument {
  asset_id: number;
  blob_path: string;
  content_type: string | null;
  doc_type: string;
  document_id: Generated<number>;
  file_size_bytes: number | null;
  is_active: Generated<boolean>;
  title: string;
  uploaded_at: Generated<Date>;
  uploaded_by: number;
  version: Generated<number>;
}

export interface AssetFootprint {
  asset_id: number;
  created_at: Generated<Date>;
  created_by: number;
  depth_m: number;
  footprint_id: Generated<number>;
  geometry: string;
  source_blob_path: string | null;
  source_kind: string;
  updated_at: Generated<Date>;
  width_m: number;
}

export interface AssetPlacement {
  asset_id: number;
  created_at: Generated<Date>;
  created_by: number;
  layout_id: number;
  note: string | null;
  placement_id: Generated<number>;
  rotation_deg: Generated<number>;
  valid_from: Generated<Date>;
  valid_to: Date | null;
  x_m: number;
  y_m: number;
}

export interface AssetProcess {
  asset_id: number;
  process_id: number;
}

export interface AssetRestriction {
  asset_id: number;
  created_at: Generated<Date>;
  description: string;
  is_active: Generated<boolean>;
  restriction_id: Generated<number>;
  restriction_type: string;
  updated_at: Generated<Date>;
}

export interface Cell {
  cell_id: Generated<number>;
  code: string;
  created_at: Generated<Date>;
  is_active: Generated<boolean>;
  line_id: number | null;
  name: string;
  plant_id: number;
  sequence_in_line: number | null;
  updated_at: Generated<Date>;
}

export interface DatabaseFirewallRules {
  create_date: Date;
  end_ip_address: string;
  id: Generated<number>;
  modify_date: Date;
  name: unknown;
  start_ip_address: string;
}

export interface Department {
  created_at: Generated<Date>;
  department_id: Generated<number>;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Date>;
}

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string | null;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Date>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface Invitation {
  accepted_at: Date | null;
  created_at: Generated<Date>;
  created_by: number | null;
  expires_at: Date;
  invitation_id: Generated<number>;
  token_hash: string;
  user_id: number;
}

export interface MaintenancePlan {
  asset_id: number;
  created_at: Generated<Date>;
  description: string | null;
  estimated_minutes: number | null;
  frequency_unit: string;
  frequency_value: number;
  is_active: Generated<boolean>;
  name: string;
  next_due_date: Date | null;
  plan_id: Generated<number>;
  plan_type: string;
  schedule_mode: Generated<string>;
  updated_at: Generated<Date>;
}

export interface NavItem {
  created_at: Generated<Date>;
  href: string;
  icon: string | null;
  is_active: Generated<boolean>;
  item_id: Generated<number>;
  label: string;
  parent_item_id: number | null;
  section_id: number;
  sort_order: Generated<number>;
  updated_at: Generated<Date>;
}

export interface NavSection {
  base_path: string;
  code: string;
  created_at: Generated<Date>;
  icon: string | null;
  is_active: Generated<boolean>;
  label: string;
  section_id: Generated<number>;
  sort_order: Generated<number>;
  updated_at: Generated<Date>;
}

export interface Permission {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  permission_id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface PlanMaterial {
  plan_id: number;
  plan_material_id: Generated<number>;
  quantity: number;
  spare_part_id: number;
}

export interface Plant {
  address: string | null;
  code: string;
  created_at: Generated<Date>;
  is_active: Generated<boolean>;
  name: string;
  plant_id: Generated<number>;
  postal_code: string | null;
  updated_at: Generated<Date>;
}

export interface PlanTask {
  instructions: string | null;
  plan_id: number;
  plan_task_id: Generated<number>;
  seq: number;
  title: string;
  visual_aid_document_id: number | null;
}

export interface PlantLayout {
  activated_at: Date | null;
  archived_at: Date | null;
  created_at: Generated<Date>;
  created_by: number;
  geometry: string;
  height_m: number;
  layout_id: Generated<number>;
  name: string;
  note: string | null;
  plant_id: number;
  source_blob_path: string;
  status: Generated<string>;
  version: number;
  width_m: number;
}

export interface PlantProcess {
  plant_id: number;
  process_id: number;
}

export interface Process {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  process_id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ProductionLine {
  code: string;
  created_at: Generated<Date>;
  is_active: Generated<boolean>;
  line_id: Generated<number>;
  name: string;
  plant_id: number;
  updated_at: Generated<Date>;
}

export interface Role {
  department_id: number | null;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  role_id: Generated<number>;
}

export interface RoleNavItem {
  item_id: number;
  priority: Generated<number>;
  role_id: number;
}

export interface RoleNavSection {
  priority: Generated<number>;
  role_id: number;
  section_id: number;
}

export interface RolePermission {
  permission_id: number;
  role_id: number;
}

export interface RunLog {
  entity: string;
  finished_at: Date | null;
  message: string | null;
  rows_loaded: number | null;
  run_id: Generated<number>;
  started_at: Generated<Date>;
  status: Generated<string>;
  watermark: string | null;
}

export interface SparePart {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  is_active: Generated<boolean>;
  min_stock: number | null;
  name: string;
  spare_part_id: Generated<number>;
  unit_cost: number | null;
  uom: Generated<string>;
  updated_at: Generated<Date>;
}

export interface StockMovement {
  moved_at: Generated<Date>;
  moved_by: number;
  movement_type: string;
  note: string | null;
  quantity: number;
  spare_part_id: number;
  stock_movement_id: Generated<number>;
  work_order_id: number | null;
}

export interface UserDepartment {
  department_id: number;
  user_id: number;
}

export interface UserPlant {
  plant_id: number;
  user_id: number;
}

export interface UserRole {
  role_id: number;
  user_id: number;
}

export interface WorkOrder {
  asset_id: number;
  assigned_to: number | null;
  code: Generated<string | null>;
  completed_at: Date | null;
  completed_by: number | null;
  created_at: Generated<Date>;
  downtime_minutes: number | null;
  notes: string | null;
  plan_id: number | null;
  scheduled_date: Date;
  started_at: Date | null;
  status: Generated<string>;
  updated_at: Generated<Date>;
  wo_type: string;
  work_order_id: Generated<number>;
}

export interface WorkOrderMaterial {
  quantity: number;
  spare_part_id: number;
  work_order_id: number;
  work_order_material_id: Generated<number>;
}

export interface WorkOrderTask {
  comment: string | null;
  done_at: Date | null;
  done_by: number | null;
  instructions: string | null;
  is_done: Generated<boolean>;
  seq: number;
  title: string;
  work_order_id: number;
  work_order_task_id: Generated<number>;
}

export interface DB {
  app_user: AppUser;
  asset: Asset;
  asset_cell_assignment: AssetCellAssignment;
  asset_document: AssetDocument;
  asset_footprint: AssetFootprint;
  asset_placement: AssetPlacement;
  asset_process: AssetProcess;
  asset_restriction: AssetRestriction;
  cell: Cell;
  database_firewall_rules: DatabaseFirewallRules;
  department: Department;
  flyway_schema_history: FlywaySchemaHistory;
  invitation: Invitation;
  maintenance_plan: MaintenancePlan;
  nav_item: NavItem;
  nav_section: NavSection;
  permission: Permission;
  plan_material: PlanMaterial;
  plan_task: PlanTask;
  plant: Plant;
  plant_layout: PlantLayout;
  plant_process: PlantProcess;
  process: Process;
  production_line: ProductionLine;
  role: Role;
  role_nav_item: RoleNavItem;
  role_nav_section: RoleNavSection;
  role_permission: RolePermission;
  run_log: RunLog;
  spare_part: SparePart;
  stock_movement: StockMovement;
  user_department: UserDepartment;
  user_plant: UserPlant;
  user_role: UserRole;
  work_order: WorkOrder;
  work_order_material: WorkOrderMaterial;
  work_order_task: WorkOrderTask;
}
