/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AppUser {
  all_plants: Generated<boolean>;
  created_at: Generated<Date>;
  display_name: string | null;
  email: string | null;
  is_active: Generated<boolean>;
  password_hash: string | null;
  token_version: Generated<number>;
  updated_at: Generated<Date>;
  user_id: Generated<number>;
  username: string;
}

export interface DatabaseFirewallRules {
  create_date: Date;
  end_ip_address: string;
  id: Generated<number>;
  modify_date: Date;
  name: unknown;
  start_ip_address: string;
}

export interface Department {
  created_at: Generated<Date>;
  department_id: Generated<number>;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Date>;
}

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string | null;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Date>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface Invitation {
  accepted_at: Date | null;
  created_at: Generated<Date>;
  created_by: number | null;
  expires_at: Date;
  invitation_id: Generated<number>;
  token_hash: string;
  user_id: number;
}

export interface Plant {
  address: string | null;
  code: string;
  created_at: Generated<Date>;
  is_active: Generated<boolean>;
  name: string;
  plant_id: Generated<number>;
  postal_code: string | null;
  updated_at: Generated<Date>;
}

export interface Report {
  category_id: number | null;
  created_at: Generated<Date>;
  dataset_guid: string | null;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  report_guid: string;
  report_id: Generated<number>;
  sort_order: Generated<number>;
  updated_at: Generated<Date>;
  workspace_guid: string;
}

export interface ReportCategory {
  category_id: Generated<number>;
  name: string;
  sort_order: Generated<number>;
}

export interface Role {
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  role_id: Generated<number>;
}

export interface RunLog {
  entity: string;
  finished_at: Date | null;
  message: string | null;
  rows_loaded: number | null;
  run_id: Generated<number>;
  started_at: Generated<Date>;
  status: Generated<string>;
  watermark: string | null;
}

export interface UserDepartment {
  department_id: number;
  user_id: number;
}

export interface UserPlant {
  plant_id: number;
  user_id: number;
}

export interface UserRole {
  role_id: number;
  user_id: number;
}

export interface DB {
  app_user: AppUser;
  database_firewall_rules: DatabaseFirewallRules;
  department: Department;
  flyway_schema_history: FlywaySchemaHistory;
  invitation: Invitation;
  plant: Plant;
  report: Report;
  report_category: ReportCategory;
  role: Role;
  run_log: RunLog;
  user_department: UserDepartment;
  user_plant: UserPlant;
  user_role: UserRole;
}
